apiVersion: v1
kind: Pod
metadata:
  name: pod-gff-mongo-db
  labels:
    app: pod-gff-mongo-db
spec:
  containers:
    - name: mongodb
      image: mongo:4.2.8
      ports:
        - containerPort: 27017