services:

  app:
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
    networks:
      - gff-compose-network

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - gff-compose-network

networks:
  gff-compose-network:
    driver: bridge

volumes:
  data: