apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-gff-mongo-db
  name: svc-gff-mongo-db
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: pod-gff-mongo-db