apiVersion: v1
kind: Pod
metadata:
  name: pod-gff-mongo-db
  labels:
    app: pod-gff-mongo-db
spec:
  hostname: pod-gff-mongo-db
  containers:
    - name: mongodb
      image: mongo:4.2.8
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
      ports:
        - containerPort: 27017