apiVersion: v1
kind: Pod
metadata:
  name: pod-gff-api
spec:
  containers:
  - name: pod-gff-api
    image: ritchellydomingos/gff
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: prod
    ports:
    - containerPort: 8080