apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-gff-api
  name: svc-gff-api
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: pod-gff-api